---
swagger: "2.0"
info:
  description: "Documentatie API pentru Checksum Checker, o aplicatie dezvoltata pe durata modulului Programare Concurenta si Distributiva<br /><br />\
    \ Universitatii de Vest Timisoara<br /><br />\
    \ Facultatea de Matematica si Informatica<br /><br />\
    \ Domeniu Informatica<br /><br />\
    \ Sectia Informatica Aplicata<br /><br />\
    \ An 3<br /><br />\
    \ Semestrul 2, anul 2022.<br /><br />\
    \ <b>Authors</b>:<br />\
    \ - Andrei Jucan<br />\
    \ - Gabriel Mares<br />\
    \ - Lascu-Adelin Craciunesc<br />\
    \ - Bogdan Dragos"
  version: "1.0"
  title: "Checksum Checker API"
tags:
- name: "client"
  description: "API calls disponibile tuturor utilizatorilor aplicatiei"

paths:
  /verify-checksum:
    post:
      tags:
      - "client"
      summary: "Permite oricarui client sa-si compare checksum-ul fisierului lui cu cel existent in aplicatia noastra"
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              algorithm:
                type: integer
                example: 3
                description: "3 represents SHA256. Refer to Discord client's pcd.algorithms command for a 1:1 list of relations between this integer and the desired algorithm"
              checksum:
                type: string
                example: "32471304294102794107"
              file:
                type: string
                format: byte
              
      responses:
        200:
          description: "Successful operation"
          schema:
            type: object
            properties:
              matches:
                type: string
                example: "OK or NOK"
  /checksum:
    post:
      tags:
      - "client"
      summary: "Permite oricarui client sa urce pe aplicatie un fisier pentru a-i fi generat checksum-ul"
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              algorithm:
                type: integer
                example: 3
                description: "3 represents SHA256. Refer to Discord client's pcd.algorithms command for a 1:1 list of relations between this integer and the desired algorithm"
              file:
                type: string
                format: byte
      responses:
        200:
          description: "Successful operation"
          schema:
            type: object
            properties:
              checksum:
                type: string
                example: "32471304294102794107"