---
swagger: "2.0"
info:
  description: "Documentatie API pentru Checksum Checker, o aplicatie dezvoltata pe durata modulului Programare Concurenta si Distributiva<br /><br />\
    \ Universitatii de Vest Timisoara<br /><br />\
    \ Facultatea de Matematica si Informatica<br /><br />\
    \ Domeniu Informatica<br /><br />\
    \ Sectia Informatica Aplicata<br /><br />\
    \ An 3<br /><br />\
    \ Semestrul 2, anul 2022.<br /><br />\
    \ <b>Authors</b>:<br />\
    \ - Andrei Jucan<br />\
    \ - Gabriel Mares<br />\
    \ - Lascu-Adelin Craciunesc<br />\
    \ - Bogdan Dragos"
  version: "1.0"
  title: "Checksum Checker API"
tags:
- name: "admin"
  description: "API calls disponibile doar clientului admin"
- name: "client"
  description: "API calls disponibile tuturor utilizatorilor aplicatiei"

paths:
  /algorithm:
    patch:
      tags:
      - "admin"
      summary: "Permite clientului admin sa activeze sau sa dezactiveze un algoritm dezactivat anterior"
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              algorithm:
                type: string
                example: "SHA-256"
      responses:
        200:
          description: "Successful operation"
        403:
          description: "Client neautorizat - Se va folosi doar clientul admin UNIX"
  /sensitiveFile:
    delete:
      tags:
      - "admin"
      summary: "Permite clientului admin sa stearga anumite fisiere sensitive sau cu repercusiuni legale"
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              path:
                type: string
                example: "SHA-256/definetlyNotCP.jpeg"
              file (optional):
                type: string
                format: byte
      responses:
        200:
          description: "Successful operation"
        403:
          description: "Client neautorizat - Se va folosi doar clientul admin UNIX"
        500:
          description: "Fisier neexistent"
  /checksum:
    get:
      tags:
      - "client"
      summary: "Permite oricarui client sa-si compare checksum-ul fisierului lui cu cel existent in aplicatia noastra"
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              filename:
                type: string
                example: "safefile.exe"
              file:
                type: string
                format: byte
              checksum:
                type: string
                example: "32471304294102794107"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: object
            properties:
              matches:
                type: boolean
        404:
          description: "Nu exista in cadrul aplicatiei un fisier cu acel nume. Generati un checksum intai prin metoda put"
    post:
      tags:
      - "client"
      summary: "Permite oricarui client sa urce pe aplicatie un fisier pentru a-i fi generat checksum-ul"
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              filename:
                type: string
                example: "saeffile.exe"
              file:
                type: string
                format: byte
      responses:
        200:
          description: "Successful operation"
          schema:
            type: object
            properties:
              checksum:
                type: string
                example: "32471304294102794107"